### ISSUE TITLE
Variables for tasks

### ISSUE THREAD

**Issue by joreg** [vvvv/Remoter#13]
quest: in a mirror task i want to specify that individual target pc's get individual files from the source.

example:
source has files arranged like:
C:\temp\A
C:\temp\B
C:\temp\C

i want PC with alias "A" to receive only files from C:\temp\A and PC with alias "B" only files from C:\temp\B

so in the mirror source folder i want to be able to specify: C:\temp\<Alias>

**Comment by antongit** [comment]
Closed by 8e5c47818d9f9f431ad0f535685348f9db7e9194
